### ISSUE TITLE
createListener or createServer 

### ISSUE THREAD

**Issue by wanderer** [diasdavid/interface-transport#2]
I found createListener to be a bit confusing. Is there a better name we could use? Will it somehow deviate from what createServer is suppose to do?

**Comment by diasdavid** [comment]
The rationale between listener vs server, or even dialer vs client, is that the client-server nomenclature carries a great weight in how developers think of their applications which causes some confusion when talking about P2P applications. There is some differences, depending on which peer is calling the other (therefore dialer vs listener), but once the connection is setup, no preconceived notion of "who is serving" or "who is requesting" should be implied.

**Comment by wanderer** [comment]
ok that sounds good! Thanks for the answer. :)
